using System.Text.Json;
using System.Text.Json.Serialization;

namespace LlamaCpp.Bindings;

/// <summary>
/// Provenance metadata for a <see cref="LlamaSensitivityProfile"/> —
/// where the coefficients came from, so a downstream consumer can
/// judge how much to trust them.
/// </summary>
/// <remarks>
/// Profiles can be authored three ways: measured via ablation
/// (<see cref="LlamaSensitivityProfileBuilder"/>), hand-written from
/// observation or literature, or imported from another tool's output.
/// The recipe builder treats them identically; a human reading the
/// file should be able to tell which is which.
/// </remarks>
public sealed record LlamaSensitivityProvenance(
    string Method,                  // "ablation" | "hand-authored" | "imported"
    string? SourceModel,            // file name of the model the coefficients describe
    long? SourceParameterCount,     // total parameter count of SourceModel (recipe builder uses this for size-scaling)
    string? Corpus,                 // calibration corpus name (only meaningful for ablation)
    DateTime? BuiltAtUtc,
    string? BuilderVersion);        // tool + version, for "this profile was generated by X"

/// <summary>
/// Per-category quantization sensitivity coefficient measured by ablation:
/// for each candidate <see cref="LlamaTensorType"/>, how much wikitext-PPL
/// goes up when only this category is quantized to that type and the rest
/// stays at F16.
/// </summary>
/// <remarks>
/// Built by <see cref="LlamaSensitivityProfileBuilder"/>. The recipe builder
/// uses <see cref="DeltaPplByType"/> to score candidate recipes (sum the
/// per-(category, type) ΔPPL across all categories) and to honor the
/// <see cref="RecommendedFloor"/> — a "do not go below this type" guardrail
/// derived from the knee in the curve.
/// </remarks>
public sealed record LlamaSensitivityCategoryCoefficient(
    Dictionary<LlamaTensorType, double> DeltaPplByType,
    LlamaTensorType? RecommendedFloor,
    string? Notes = null);

/// <summary>
/// Per-architecture quantization sensitivity profile. Captures how each
/// tensor category responds to being quantized at various bit-widths,
/// measured against an F16 baseline on a calibration corpus.
/// </summary>
/// <remarks>
/// <para>
/// Profiles are slow to build (~14 min on Qwen3-0.6B with the parallel PPL
/// runner; longer on bigger models) but cheap to apply. Build once per
/// architecture family; the recipe builder applies size scaling when the
/// target model differs from the profile's source.
/// </para>
/// <para>
/// The on-disk format is JSONC (JSON with line comments and trailing
/// commas). This is the declarative artifact the recipe builder reads
/// — a human can hand-author one from a paper or intuition by setting
/// <see cref="LlamaSensitivityProvenance.Method"/> to <c>"hand-authored"</c>
/// and filling in coefficients without running the ablation campaign.
/// </para>
/// </remarks>
public sealed record LlamaSensitivityProfile(
    int SchemaVersion,
    string ArchitectureId,
    int LayerCount,
    string? FamilyNotes,
    LlamaSensitivityProvenance Provenance,
    double F16BaselinePerplexity,
    int BaselineContextSize,
    Dictionary<string, LlamaSensitivityCategoryCoefficient> Categories)
{
    /// <summary>Current schema version. Bump on incompatible changes.</summary>
    public const int CurrentSchemaVersion = 1;

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        Converters = { new JsonStringEnumConverter() },
        NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals,
        ReadCommentHandling = JsonCommentHandling.Skip,        // tolerate hand-authored comments
        AllowTrailingCommas = true,                            // tolerate trailing commas after edits
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    };

    public static LlamaSensitivityProfile LoadFromJson(string path)
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        var json = File.ReadAllText(path);
        var profile = JsonSerializer.Deserialize<LlamaSensitivityProfile>(json, JsonOpts)
            ?? throw new InvalidDataException($"Failed to deserialize profile from {path}.");
        if (profile.SchemaVersion > CurrentSchemaVersion)
        {
            throw new InvalidDataException(
                $"Profile {path} is schema v{profile.SchemaVersion}, this build understands up to " +
                $"v{CurrentSchemaVersion}. Upgrade the bindings or downgrade the profile.");
        }
        return profile;
    }

    public void SaveToJson(string path)
    {
        ArgumentException.ThrowIfNullOrEmpty(path);
        var dir = Path.GetDirectoryName(path);
        if (!string.IsNullOrEmpty(dir)) Directory.CreateDirectory(dir);
        File.WriteAllText(path, JsonSerializer.Serialize(this, JsonOpts));
    }

    /// <summary>
    /// Categories ordered most-sensitive-first per F16-relative ΔPPL at Q4_K.
    /// Computed property — not serialized.
    /// </summary>
    [JsonIgnore]
    public IEnumerable<string> CategoriesByDescendingSensitivityAtQ4K =>
        Categories
            .OrderByDescending(kv => kv.Value.DeltaPplByType.GetValueOrDefault(LlamaTensorType.Q4_K, 0.0))
            .Select(kv => kv.Key);
}
